 # Subscriptions to EOS-Native paths.
subscriptions:
        - /Kernel/proc/cpu/utilization/
        - /Sysdb/interface/status/eth/phy/slice/1/intfStatus/
        - /Smash/routing/bgp
# Prometheus metrics configuration.
# If you use named capture groups in the path, they will be extracted into labels with the same name.
# All fields are mandatory.

metrics:
        - name: cpuinfo
          path: /Kernel/proc/cpu/utilization/total/(?P<usageType>(?:system|user|idle))
          help: CPU Info
        - name: basestatus
          path: /Sysdb/interface/status/eth/phy/slice/1/intfStatus/(?P<intf>.+)/linkStatus
          help: BaseStatus
          valuelabel: linkStatus
          defaultvalue: 0
        - name: bgppeerstatus
          path: /Smash/routing/bgp/bgpPeerInfoStatus/default/bgpPeerStatusEntry/(?P<peerAddress>.+)/bgpState
          help: BGP Peer status
          valuelabel: bgpState
          defaultvalue: 0
